[package]
name = "ez_wasm_bindgen_static_closure"
version = "0.1.0"
authors = ["zperk13"]
edition = "2021"

[lib]
proc_macro=true

[dependencies]
wasm-bindgen = "0.2.81"
syn = "1.0.98"
quote = "1.0.20"
